services:
  astro:
    image: node:22-alpine
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
    ports:
      - "${NODE_PORT}:4321"
    environment:
      - NODE_ENV=development
      - MAX_CPU=${MAX_CPU:-1}
      - HOST=0.0.0.0
    stdin_open: true
    restart: unless-stopped

volumes:
  node_modules:
